spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_udemy
    username: evoge_user
    password: evoge_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
