spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_udemy
    username: evoge_user
    password: evoge_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
